---
- name: "Docker Image Build From Github Push Event"
  hosts: Build
  become: true
  vars:
    repo_url: "https://github.com/Swathikarun/docker-python-flask.git"
    repo_dest: "/var/repo"
    image_name: "swathikarun/flaskapp"
    docker_password: "Sw@th!k@4"
  tasks:
    
    - name: "Build - Installing Docker"
      shell: 'amazon-linux-extras install docker -y'
      args:
       warn: no
 
    - name: "Build - Installing Additional Package"
      yum:
        name: git,python-pip
        state: present


    - name: "Build - Installing Python Docker Extension"
      pip:
        name: docker-py

    - name: "Build - Restarting/Enable Docker service"
      service:
        name: docker
        state: restarted
        enabled: true

    - name: "Build - Cloning Repository"
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
      register: repo_status



    - name: "Build - Login to Remote Repository"
      when: repo_status.changed == true
      docker_login:
        username: swathikarun
        password: "{{ docker_password }}"

            
            
    - name: "Build - Building the image"
      when: repo_status.changed == true
      docker_image:
        source: build
        build:
          path: "{{ repo_dest }}"
          pull: yes
        name: "{{ image_name }}"
        tag: "{{ item }}"
        push: true
        force_tag: yes
        force_source: yes
      with_items:
        - "{{ repo_status.after }}"
        - latest
    

    - name: "Build - Removing the image"
      when: repo_status.changed == true
      docker_image:
        state: absent
        name: "{{ image_name }}"
        tag: "{{ item }}"
      with_items:
        - "{{ repo_status.after }}"
        - latest



- name: "Docker Run Container"
  hosts: Test
  become: true
  vars:
    image_name: "swathikarun/flaskapp"
    
  tasks:
    
    - name: "Deployment - Installing Docker"
      shell: 'amazon-linux-extras install docker -y'
      args:
        warn: no

            
    - name: "Deployment - Installing Additional package"
      yum:
        name: python-pip
        state: present


    - name: "Deployment - Installing Python Docker Extension"
      pip:
        name: docker-py

    - name: "Deployment - Restarting/Enable Docker service"
      service:
        name: docker
        state: restarted
        enabled: true

    - name: "Deployment - Run Container"
      docker_container:
        name: webserver
        image: "{{ image_name }}:latest"
        recreate: yes
        pull: yes
        published_ports:
          - "80:5000"
